### ISSUE TITLE
求助样式丢失问题

### ISSUE THREAD

**Issue by monan19920722** [y805939188/react-vue-micro-frame#7]
大佬，非常喜欢这个组件。我的场景是上传一个自己打包好的组件，然后返回一个url，通过您的这个去加载（预览）上传的组件。第一次预览没有问题，当我第二次再预览的时候相当于重新挂在了您的这个组件。我自己组件的样式就出不来了，样式是通过css-loader打包在js中的。求大佬指点

**Comment by y805939188** [comment]
你好，能否提供一下更详细的使用方式，比如是如何重新挂载的。我尝试复现一下

**Comment by y805939188** [comment]
> 大佬，非常喜欢这个组件。我的场景是上传一个自己打包好的组件，然后返回一个url，通过您的这个去加载（预览）上传的组件。第一次预览没有问题，当我第二次再预览的时候相当于重新挂在了您的这个组件。我自己组件的样式就出不来了，样式是通过css-loader打包在js中的。求大佬指点

你好，能否提供一下更详细的使用方式，比如是如何重新挂载的。我尝试复现一下

**Comment by monan19920722** [comment]
我这边用的是react，大概操作是点击上传后用useState将预览的位置改成空白（相当于卸载了您的组件），上传成功后返回一个url。再useState把您这个组件挂上去。如果可以留个联系方式呗，扣扣：465706912。感谢！

**Comment by y805939188** [comment]
> 我这边用的是react，大概操作是点击上传后用useState将预览的位置改成空白（相当于卸载了您的组件），上传成功后返回一个url。再useState把您这个组件挂上去。如果可以留个联系方式呗，扣扣：465706912。感谢！

我Q是 805939188，可以加我一起交流

**Comment by y805939188** [comment]
resolved by commit [80a7563](https://github.com/y805939188/react-vue-micro-frame/commit/80a7563fa1eb40b0ac00b937f2e985b379ef4794)
